AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nestedstackscf161282/14efb51badf27ec94ad8a3f4429c26c7.template
  LambdaS3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nestedstackscf161282/c64e98faaae5075414254dce784e1b26.template
