AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VPCName:
    Description: The name of the VPC being created.
    Type: String
    Default: "Team3"
  # S3BucketName:
  #   Description: Enter S3 Bucket Name
  #   Type: String
  #   MinLength: 3
  #   AllowedPattern: '^[A-Za-z0-9_-]*$'
  #   Default: "cloudpracticum1612"
Resources:
  myVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        -
          Key: "Name"
          Value: !Ref 'VPCName'

  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-1a
      Tags:
        -
          Key: "Name"
          Value: !Ref 'VPCName'

  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1a
      Tags:
        -
          Key: "Name"
          Value: !Ref 'VPCName'

  myVPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref myGateway
      VpcId: !Ref myVPC

  myGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        -
          Key: "Name"
          Value: !Ref 'VPCName'
 
  myRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref myVPC
      Tags:
        -
          Key: "Name"
          Value: !Ref 'VPCName'

  mySubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref myRouteTable

  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref myRouteTable
      GatewayId: !Ref myGateway
      DestinationCidrBlock: 0.0.0.0/0
    DependsOn:
      - myVPCGatewayAttachment
  # MyS3Bucket:
  #   Type: 'AWS::S3::Bucket'
  #   Properties:
  #     BucketName: !Ref S3BucketName

Outputs:
  VPC:
    Description: VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPC
    Value: !Ref myVPC

  PublicSubnet:
    Description: PublicSubnet
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet
    Value: !Ref PublicSubnet

  PrivateSubnet:
    Description: PrivateSubnet
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet
    Value: !Ref PrivateSubnet